### ISSUE TITLE
for help: code raise a exception

### ISSUE THREAD

**Issue by CogmanCVN** [erikbern/ann-benchmarks#104]
when runing install.py this line of code raise a exception，
subprocess.check_call( 'docker build \   --rm -t ann-benchmarks -f install/Dockerfile .', shell=True) 
Exception is：
subprocess.CalledProcessError: Command 'docker build         --rm -t ann-benchmarks -f install/Dockerfile .' returned non-zero exit status 1.
I hope you can help me

**Comment by appusom** [comment]
Is there any solution to this problem? I am facing the same on Ubuntu 16.04.

**Comment by erikbern** [comment]
Does it print a bunch of stuff to standard out? Can you share?

**Comment by appusom** [comment]
I finally resolved this issue by ensuring the docker daemon was running correctly before I ran this code. Thanks.

**Comment by pramodv1993** [comment]
Hello, I too am facing the same issue once I try to run the install.py script, Is there a solution for the same?

**Comment by maumueller** [comment]
What does it say if you run ` docker build --rm -t ann-benchmarks -f install/Dockerfile .` in your terminal (in the ann-benchmarks directory)?

**Comment by yurymalkov** [comment]
I also has experienced errors with the docker build, probably due to ubuntu update.
Changing the first line of the docker file to `FROM ubuntu:18.04` helped me.

**Comment by pramodv1993** [comment]
> What does it say if you run ` docker build --rm -t ann-benchmarks -f install/Dockerfile .` in your terminal (in the ann-benchmarks directory)?

Hello Sir, I tried the suggestion by Yury Malkov, it now passed the step6/7 of  RUN pip3 install -rrequirements.txt :)

**Comment by pramodv1993** [comment]
> I also has experienced errors with the docker build, probably due to ubuntu update.
> Changing the first line of the docker file to `FROM ubuntu:18.04` helped me.
Hello Sir, this helped pass the step where I had got stuck. Thank you :)
