### ISSUE TITLE
Add SPTAG

### ISSUE THREAD

**Issue by maumueller** [erikbern/ann-benchmarks#118]
This looks interesting: https://github.com/microsoft/SPTAG

**Comment by sinkpoint** [comment]
Bump, came here to say the same thing. Microsoft just announced this.

**Comment by erikbern** [comment]
looks pretty cool!

**Comment by jerry-rubikloud** [comment]
I haven't try yet but it looks like it provides "update" function too.

**Comment by ownchoice** [comment]
They even called it "A library for **fast** approximate nearest neighbor search".

**Comment by searchivarius** [comment]
@maumueller @erikbern do we have results yet? Thanks!

**Comment by erikbern** [comment]
@searchivarius i'll re-run the benchmark in the next couple of months

**Comment by maumueller** [comment]
@erikbern Any reason to not just rerun SPTAG on an ec2 instance to have some results in? (I can do that.)

**Comment by searchivarius** [comment]
@maumueller for methods that are far from the top, there's certainly little need for re-running, but I would think one needs to re-run a few top methods on the same machine as the difference from 1 year ago in hardware might matter a bit.

**Comment by erikbern** [comment]
there's probably updates to a lot of the libraries as well, would make sense to re-run all of them

**Comment by erikbern** [comment]
SPTAG was added in #119 so i'll close this

**Comment by searchivarius** [comment]
Thank you @erikbern

**Comment by chasingegg** [comment]
Hello, since SPTAG has been added into this library, but why the figure in readme does not show the performance of SPTAG?

**Comment by erikbern** [comment]
@chasingegg it's just been a long time since the last time i ran a benchmark. probably worth doing again
