### ISSUE TITLE
About SPTAG test results

### ISSUE THREAD

**Issue by MrHwc** [erikbern/ann-benchmarks#123]
I tested it with a GIST data set，The size of the query vector is (1000*960)，Return 100 neighbors，I used the official default parameters，The time I built the index is 20562.084 s，The query time is 35.082 s，recall is 0.92669，The time to add 100 vectors is 22.281 s. I feel this time is very long, am I using it correctly? Its index construction and query time are longer than NSG. Can you give SPTAG test reference results?
my machine:
Intel(R) Xeon(R) Silver 4116 CPU @ 2.10GHz
Ubuntu 18.04
python3

**Comment by erikbern** [comment]
yeah that sounds unreasonable. i'll look at it in a few months when i re-run the results

**Comment by maumueller** [comment]
Hi @MrHwc 

How you talk about the measurements, it doesn't seem that you run it in ann-benchmarks, right?

I just had a quick go on fashion-mnist (fewer points, but also high dimensional).

```
Parameters                                 Recall      Queries per Second
Sptag(metric=L2, algo=BKT, check=4000)        0.998      343.924
Sptag(metric=L2, algo=BKT, check=50)        0.903      977.190
Sptag(metric=L2, algo=BKT, check=200)        0.933      901.778
Sptag(metric=L2, algo=KDT, check=400)        0.951     1597.451
Sptag(metric=L2, algo=BKT, check=10)        0.903      972.951
Sptag(metric=L2, algo=KDT, check=4000)        0.952     1177.086
Sptag(metric=L2, algo=BKT, check=400)        0.966      756.975
Sptag(metric=L2, algo=KDT, check=5)        0.913     1335.098
Sptag(metric=L2, algo=KDT, check=200)        0.932     1767.731
Sptag(metric=L2, algo=BKT, check=100)        0.905     1009.242
Sptag(metric=L2, algo=KDT, check=2000)        0.952     1438.305
Sptag(metric=L2, algo=KDT, check=50)        0.913     1241.687
Sptag(metric=L2, algo=BKT, check=1000)        0.988      610.652
Sptag(metric=L2, algo=BKT, check=2000)        0.995      464.747
Sptag(metric=L2, algo=KDT, check=10)        0.913     1364.505
Sptag(metric=L2, algo=BKT, check=5)        0.903      907.239
Sptag(metric=L2, algo=KDT, check=1000)        0.952     1600.346
Sptag(metric=L2, algo=KDT, check=100)        0.912     1933.498
```

This looks reasonable good, given the high recall it achieves. (The influence of the `maxCheck` value doesn't really match what is written in https://github.com/microsoft/SPTAG/blob/master/docs/Parameters.md, though.) 

Index building is indeed very slow. (I ran the benchmark with `--batch` to allow multi-threaded index building.)
