### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by pombredanne** [erikbern/ann-benchmarks#13]
@erikbern Your choices of colors make the charts really hard to read... and I am cannot fathom what it would be for a color blind person. It would be great if you can pick something with more contrast and possibly avoid shades of blue/green/orange. Thanks!

**Comment by erikbern** [comment]
sure makes sense. i can fix

**Comment by pombredanne** [comment]
@erikbern Thank you my lord!

**Comment by erikbern** [comment]
Btw the data and the plot script is in the repo, so feel free to update it yourself :)

**Comment by pombredanne** [comment]
I will try, though that removes a bit of the charm of having you handle all the setup ;)
And http://matplotlib.org/users/colormaps.html seems to have too many choices...

**Comment by erikbern** [comment]
you don't need any setup for the plotting, i think cloning the repo and running plot.py should be enough :)

but i can take a look at this too

**Comment by erikbern** [comment]
better now? :)

**Comment by pombredanne** [comment]
Thank you++. I can see clearly now.
