### ISSUE TITLE
Add N2 ?

### ISSUE THREAD

**Issue by vprelovac** [erikbern/ann-benchmarks#130]
This one is promising:
https://github.com/kakao/n2

**Comment by erikbern** [comment]
just glancing at the readme, definitely seems interesting.

@ummae – would you be interested in submitting a pull request to add n2 to the benchmarks?

**Comment by ummae** [comment]
@erikbern Okay, I will.

**Comment by erikbern** [comment]
great @ummae ! no rush

**Comment by erikbern** [comment]
Ping @ummae do you want to contribute with it? I'd love to re-run the benchmarks soon

**Comment by ummae** [comment]
@erikbern Sorry for late. This work is being delayed as we are preparing major update of N2. It will be updated in next 3-4 weeks (I hope so). It would be nice if anyone could contribute before then.
