### ISSUE TITLE
Redirect http://www.itu.dk/people/pagh/SSS/ann-benchmarks/ to ann-benchmarks.com

### ISSUE THREAD

**Issue by erikbern** [erikbern/ann-benchmarks#132]
There was a hacker news thread linking to the itu.dk page: https://news.ycombinator.com/item?id=21374400

Probably makes sense to remove that page and redirect to ann-benchmarks.com or what do you think @maumueller @ale-f ?

Reminds me it's probably time to run another benchmark soon. There's been some additions lately.

**Comment by maumueller** [comment]
Sure, made a redirect.

**Comment by erikbern** [comment]
Awesome thanks!
