### ISSUE TITLE
Compare both Index Build time and Query Time using some sort of combined metric?

### ISSUE THREAD

**Issue by bio-info-guy** [erikbern/ann-benchmarks#135]
Is there a known metric to combine both build time and query time into a metric, for those that wish to do approximate k nearest neighbor within a different dataset each time.

**Comment by maumueller** [comment]
Hi

it would be trivial to add such a measure by adding something like <build time> + <time to answer all queries> to https://github.com/erikbern/ann-benchmarks/blob/master/ann_benchmarks/plotting/metrics.py and plotting this against recall in https://github.com/erikbern/ann-benchmarks/blob/master/ann_benchmarks/plotting/plot_variants.py. 

However, I'm not sure if it provides much more information than inspecting the recall/build time plot on the web site (e.g., http://ann-benchmarks.com/glove-100-angular_10_angular.html).

Martin
