### ISSUE TITLE
plot.py does not plot 

### ISSUE THREAD

**Issue by wjtan99** [erikbern/ann-benchmarks#136]
I used python plot.py --dataset=glove-100-angular to plot the results after the simulations are done. The results are in results/glove-100-angular/10. 
But it does not plot. Instead, it says  Exception: Nothing to plot
I tracked into compute_metrics in utils.py and found that the res is empty.  
Can you help me out?

**Comment by maumueller** [comment]
Could you try to run `plot.py` with `sudo`? I think the plotting script writes to the result files for caching and might run into permission errors.

**Comment by wjtan99** [comment]
Thanks a lot for your very quick response. Yes, that is cause. I can either run with a sudo or remove the "+" in the following line in results.py 

f = h5py.File(os.path.join(root, fn), 'r+')

**Comment by wjtan99** [comment]
Another problem.  I guess this may be some env setup issue 

Traceback (most recent call last):
  File "plot.py", line 139, in <module>
    linestyles, args.batch)
  File "plot.py", line 28, in create_plot
    for algo in sorted(all_data.keys(), key=lambda x: x.lower()):
TypeError: '<' not supported between instances of 'str' and 'bytes'

**Comment by wjtan99** [comment]
Later on I found I should not remove "+" in that line. 
Anyway, all problem resolved now.
