### ISSUE TITLE
Any plan to test even higher dimensional data?

### ISSUE THREAD

**Issue by dafukua** [erikbern/ann-benchmarks#14]
It'll be very interesting to see the comparisons between different suitable methods for higher dimensional data (e.g., several thousands or even larger).

Thank you.

**Comment by erikbern** [comment]
might actually run a test with 1000D... was thinking about that. would be fun

**Comment by searchivarius** [comment]
Why not trying sparse TF*IDF?

**Comment by erikbern** [comment]
Does any of the libraries support sparse data?

Btw I tried running a 1000D dataset (word2vec on freebase) yesterday but the code isn't very memory efficient so I had to rent a r3.8xlarge (244GB)... was super slow and unfortunately my spot instance was killed later. I think I need to fix up the scripts before I rerun the experiments.

**Comment by searchivarius** [comment]
I am not sure how many libraries support sparse data. Anyways, if you are interested in more dimensions, here's probably a good data set:
http://disa.fi.muni.cz/profiset/
Disclaimer: I didn't use it yet, but looks promising.

**Comment by ludwigschmidt** [comment]
I think higher-dimensional dense data (say around 1000 dimensions) and very high-dimensional sparse data (say 10k - 100k dimensions) would both be very interesting benchmarks.

FALCONN (added in #16 ) supports sparse data. If other libraries also support sparse data, @ilyaraz and I can help with setting up a benchmark.

**Comment by searchivarius** [comment]
@ludwigschmidt AFAIK, currently only two libraries support sparse spaces.

**Comment by searchivarius** [comment]
But I would be all for some more tests with weird spaces at least l1 or lp with the fractional p < 1.

**Comment by erikbern** [comment]
We should test for 1000D at least. But need to improve the script a bit first.

**Comment by ludwigschmidt** [comment]
I think it would be also be interesting to consider a 1000D dataset without increasing the available memory by 10x. That would test the libraries in the regime where less memory is available.

**Comment by erikbern** [comment]
Sure. If someone has time, would really appreciate it if you can make the scripts work with larger data set. Right now it's quite inefficient – it reads the entire data set into memory (using double precision). It would be much better if we could just build up the index incrementally for instance.

**Comment by searchivarius** [comment]
@ludwigschmidt while measuring memory footprint is important (and we do it automatically in NMSLIB), I would be against arbitrary memory constraints. For one, this will become an exercise in data compression for methods that have small memory footprint already (e.g., for some still good parameters SW-graph uses 20-40% of what the data set uses, even less for some highdimensional data sets). And for another you have to consider how quickly retrieval time grows with the number of points. One may have a large index, but the method may scale better with a data set size. Taking all such factors into account, makes testing too complicated (but you would surely need to do something like this, if you plan to deploy your method on 1000 machines).

**Comment by erikbern** [comment]
The benchmark now includes results for a dataset with 960 dimensions, so I'll close this!
