### ISSUE TITLE
Consider adding a 'deep image descriptor' dataset

### ISSUE THREAD

**Issue by jtibshirani** [erikbern/ann-benchmarks#143]
In the past few years, it seems that the computer vision community transitioned away from representing images using traditional features like SIFT. It's now common to create 'deep descriptors' of images through convolutional neural nets (for example models based on the Inception architecture). It would be helpful to include a dataset of deep image descriptors to more closely represent this approach to image similarity search.

One idea is to take a sample from [this large dataset](http://sites.skoltech.ru/compvision/noimi/), which consists of images from ImageNet run through the a CNN to produce vectors. Some prominent kNN papers report results against this dataset, including [Billion-scale similarity search with GPUs](https://arxiv.org/abs/1702.08734) and [Efficient and robust approximate nearest neighbor search using Hierarchical Navigable Small World graphs](https://arxiv.org/abs/1603.09320).

**Comment by erikbern** [comment]
That's a good idea. I think the full billion is probably too much, but subsampling a few million sounds like a great idea. Maybe 10M of them (10M*96*4 = ~4GB, which should fit well into memory)

**Comment by jtibshirani** [comment]
I would be happy to open a PR to help get this started, aiming for a 10M vector subsample.

**Comment by erikbern** [comment]
sure, would definitely appreciate it

**Comment by maumueller** [comment]
I think this would be an excellent addition!

@erikbern We might want to rethink allow multi-threaded index building for such data set sizes. None of the graph-based indexes will complete within the 6 hour preprocessing time limit.

**Comment by erikbern** [comment]
@maumueller i think the plan was to use a subsample of a few million, not the full billion dataset

but sure, i'm ok enabling multithreading. let me think about how that would affect single threaded libraries during searching. i believe we used to have a thread pool to saturate all cpus

**Comment by maumueller** [comment]
I was referring to the idea of having 10M. (I'm currently experimenting with 3M 300d and it takes about 20 hours to build an HNSW index for some of its parameter choices.)

**Comment by erikbern** [comment]
we should also consider some reasonable timeout, like maybe 1-3h.
