### ISSUE TITLE
Clone the latest version of NGT

### ISSUE THREAD

**Issue by masajiro** [erikbern/ann-benchmarks#148]
[NGT](https://github.com/yahoojapan/NGT) was updated to improve the search performance especially for glove-25. When you run your benchmarks, please clone the latest version (v1.9.0) of NGT.

**Comment by erikbern** [comment]
it pulls the latest version when it installs – https://github.com/erikbern/ann-benchmarks/blob/master/install/Dockerfile.ngt

**Comment by masajiro** [comment]
My understanding is that when a git repository is cached in docker, it is not cloned, even if the repository is updated.

**Comment by erikbern** [comment]
right but i rebuild all containers from scratch every time i run the benchmarks so it's not a problem

it's been a while since last time so it's probably time soon again
