### ISSUE TITLE
performance on low dimensional datasets

### ISSUE THREAD

**Issue by suimo** [erikbern/ann-benchmarks#157]
I have tried this algorithm and flann on low dimensional dataset(3-d point cloud).
Here are 800000+ map points, and 300 query points, and find the query points' k neighbor with this algorithm and flann.
the setup of hnswlib is ef_construction = 40, M = 6.
neighbor number k = 10
the performance of two algorithm as follows:
index build time : hnswlib 2249.92 ms flann 207.523 ms
search time : hnswlib 1.3619 ms flann 0.5652 ms
and there are some difference between the search results of these two algorithm, the performance of hnswlib is worse than flann.
Is this reasonable? I'm looking forward to some advice.
here are my dataset and search result.
[dataset.tar.gz](https://github.com/erikbern/ann-benchmarks/files/4385743/dataset.tar.gz)
[flann_result.txt](https://github.com/erikbern/ann-benchmarks/files/4385744/flann_result.txt)
[hnswlib_result.txt](https://github.com/erikbern/ann-benchmarks/files/4385745/hnswlib_result.txt)

**Comment by maumueller** [comment]
I think this is rather a question for the hnswlib guys (@yurymalkov?), but it seems more than likely to me that for 3 dimensions standard tree approaches are much more efficient. (I ran some experiments for a two-dimensional dataset back in the days and `kd` was by far the fastest implementation.) 

There are some experiments on low-dimensional datasets in the HNSW lib paper https://arxiv.org/ftp/arxiv/papers/1603/1603.09320.pdf, maybe there is a hint how to set parameters in there.

**Comment by suimo** [comment]
Thanks a lot for your reply! Could you give me some advice that which algorithms are better for low dimensional dataset.

**Comment by erikbern** [comment]
might be interesting to add a very low dimensional dataset (3-10 dims) for benchmarks

**Comment by maumueller** [comment]
As said earlier, please give the standard kd tree a try, it's `--algorithm kd` in the benchmark.

With regard to low-dimensional datasets: Would be cool, but I don't know of any standard dataset :-)

**Comment by erikbern** [comment]
one idea is to just take some free data set on world cities lat/lon and project it into 3d space. i have some code for this lying around already.

**Comment by suimo** [comment]
Thanks for your reply. I will try it.
