### ISSUE TITLE
Did this benchmark consider the GPU option ?

### ISSUE THREAD

**Issue by qinjian623** [erikbern/ann-benchmarks#158]
Hi,

Since some libraries, like FAISS, have a GPU version, I'm not sure whether the test use any GPU hardware.

Thanks.

**Comment by erikbern** [comment]
You can run it with GPU enabled, but the charts shown right are for CPU only

**Comment by maumueller** [comment]
We report on runs for FAISS gpu implementations on SIFT at http://ann-benchmarks.com/ at the bottom ('batched queries').

**Comment by qinjian623** [comment]
> We report on runs for FAISS gpu implementations on SIFT at http://ann-benchmarks.com/ at the bottom ('batched queries').

Awesome, thanks for your work. 

@maumueller 
Where can I find the GPU hardware spec? 
Thanks.
