### ISSUE TITLE
Deep1b training size only ~10 Million

### ISSUE THREAD

**Issue by Briggs599** [erikbern/ann-benchmarks#164]
Just wanted to ask a quick question about the Deep1b data set. I've been interning with GSI Technology and we have been benchmarking algorithms on the Deep1b data set (see attached image for an example) and are interested in seeing how our hardware performs on very large data sets. I just wanted to ask why the Deep1b data set only has a training size of 9,990,000 instead of the full billion. I'm assuming its just so people don't accidentally try to benchmark such a large data set but I wanted to confirm with you guys first. 

Thanks for the quick response on my last question :),
Braden.

![deep-image-96-angular](https://user-images.githubusercontent.com/48164242/85183997-f23ea980-b242-11ea-8fa2-81d072ad4667.png)

**Comment by erikbern** [comment]
We only expose the first 1% of the dataset for now. Maybe at some other stage we'll do the full billion!

**Comment by Briggs599** [comment]
I just wanted to follow up and ask if you have the full deep1b dataset all prepared and just haven't implemented it or if the 10-million subset is all that is prepared. We are interested in running the full dataset on some more powerful machines. Sorry to keep bothering you :).

**Comment by erikbern** [comment]
no we don't have it prepared

**Comment by Briggs599** [comment]
Okay, we are interested in doing some true billion-scale benchmarks, if you could point us towards the code for the dataset prep we would be happy to share the code if we make changes ect. Or if you just tailored the code of the 10M set we would appreciate that code as well and any guidance you could provide. If we get it working we would love to share it with your GitHub.

**Comment by erikbern** [comment]
shouldn't be super hard to do using https://github.com/erikbern/ann-benchmarks/blob/master/ann_benchmarks/datasets.py#L197

you might have to rewrite it a bit so it doesn't brute force the solutions though and instead it just uses the provided ground truth!
