### ISSUE TITLE
Falconn not included?

### ISSUE THREAD

**Issue by musicformellons** [erikbern/ann-benchmarks#17]
Is there a specific reason why Falconn is not included?

https://github.com/falconn-lib/falconn

**Comment by erikbern** [comment]
It is included – see https://github.com/erikbern/ann-benchmarks/blob/master/ann_benchmarks/__init__.py#L21

I just haven't run the benchmark in a while. Planning to re-run it in a couple of weeks

**Comment by erikbern** [comment]
actually let me re-run it now. should be done in a day or so :)

**Comment by musicformellons** [comment]
Great, thanks!

**Comment by erikbern** [comment]
added some intermediate results, will push more results in a day or two
