### ISSUE TITLE
Faiss-lsh

### ISSUE THREAD

**Issue by Briggs599** [erikbern/ann-benchmarks#170]
We've gotten faiss-ivf working on a really large dataset (54 million vecs). Is there a reason faiss-lsh is disabled in algos.yaml? Should we not even bother using it?

**Comment by erikbern** [comment]
Sorry missed this issue. Looks like it happened in this PR: https://github.com/erikbern/ann-benchmarks/pull/74

I believe I did it because the performance was quite bad

**Comment by Briggs599** [comment]
All good ended up seeing that outcome reflected in our results. Cheers for getting back to me though!
