### ISSUE TITLE
ScaNN-only rerun?

### ISSUE THREAD

**Issue by sammymax** [erikbern/ann-benchmarks#173]
The ScaNN results currently shown on the website reflect configurations that were only tuned for Glove-100; its performance on Glove-25 and LastFM aren't really reflective of its true, properly tuned performance. I later tuned for these datasets in #172. Would it be possible to update ann-benchmarks.com to reflect these new tunings? I regret not taking more time in polishing the original submission, and I understand you plan on doing a full re-run in a few months, but in the mean time we'd prefer our Glove-25 and LastFM numbers to be more representative of our performance. I don't want every minor tweak to trigger a re-run, but 2-4x more QPS at the same recall is quite significant, and ScaNN trains quite fast so the whole thing should be doable in an hour.

**Comment by erikbern** [comment]
I might give it a month? I think the Milvus team is also eager to submit an updated implementation (see #167)

**Comment by erikbern** [comment]
Btw would love to also feature ScaNN in the Euclidean benchmarks

**Comment by sammymax** [comment]
Ok, sounds good!
