### ISSUE TITLE
Question: Why ann-benchmarks use distance to compute recall rather than id ? 

### ISSUE THREAD

**Issue by BossZou** [erikbern/ann-benchmarks#176]
I noticed that the procedure compute the distance between result vectors and query vector, and use these distances to compute recall value. However, the query results could contain vectors id, which can also be used to compute recall value. Why ann-benchmarks chose the former way?

**Comment by maumueller** [comment]
Because data points can have the same distance to the query, so "the nearest neighbor" isn't necessarily well defined. (This is particularly easy to imagine for Hamming distance and Jaccard similarity.)

**Comment by BossZou** [comment]
Thanks @maumueller , I see. I found that there are two dataset `distances` and `neighbors` in data file '*.hdf5', the shape of each dataset is (10000, 100). Is there consistent one-to-one match between those two dataset ?  For example, distance between first query vector and vector which id is `neighbors[0, 10]` is equal to `distances[0, 10]`

**Comment by maumueller** [comment]
Yes, `neighbors[0][10]` is the point with `distances[0][10]` from the first query point.

**Comment by erikbern** [comment]
I guess this can be closed?
