### ISSUE TITLE
[Question] Are there any ANN methods for sparse data?

### ISSUE THREAD

**Issue by tueboesen** [erikbern/ann-benchmarks#182]
I'm wondering if there exist any ANN method suitable for datasets with high number of dimensions but where the dimensions are sparsely populated.

I can see that the typical suggestion is to do dimensionality reduction, which I might end up doing, but before I go that route I was just wondering whether there are any alternatives.

My specific dataset are multiple sequence aligments in bioinformatics. So my data are 3D (n x L x 21). where n is the number of sequences/data points (typically between 50k-10M), L is the length of the sequences (typically somewhere around 80-500) and 21 are the different types of amino acids that each sequence can have.

So in my case I flatten the data to 2d and get (n x 21L) dimensions. However only 1 out of every 21 entries will be nonzero in this case. I'm wondering whether I can use that to my advantage somehow when computing ANN?

**Comment by yurymalkov** [comment]
You can use nmslib (https://github.com/nmslib/nmslib), it supports sparse distances.

**Comment by tueboesen** [comment]
I'm seeing speedups of around 2-3 times with that one, so that seems to work great (not sure how much of a speedup I should expect)

Thank you very much!

**Comment by erikbern** [comment]
+1 for dimensionality reduction as you mentioned
