### ISSUE TITLE
Consider HTML results output

### ISSUE THREAD

**Issue by alexkreidler** [erikbern/ann-benchmarks#192]
Several graphing libraries in python (e.g. Plotly, Vega) support outputting to interactive HTML that would make it easier for users to understand the data.

Also, you may want to consider making the output results consistent by displaying but graying out results from algorithms that either failed to return outputs or don't support a given data set. For example, `bruteforce-blas` and `scann` are not available on `sift-128-euclidean`.

Thanks for this tool!

**Comment by maumueller** [comment]
`create_website.py` generates interactive plots. See the website for examples, e.g., http://ann-benchmarks.com/glove-100-angular_10_angular.html.

**Comment by alexkreidler** [comment]
Ah, so sorry!
