### ISSUE TITLE
Default Colors are a bit hard to see on certain algorithms

### ISSUE THREAD

**Issue by stephenleo** [erikbern/ann-benchmarks#194]
The default plot colors are too light to clearly see on a white background (especially for faiss-ivf, hnsw(nmslib). I propose a slight modification to the colors to make it more readable in my opinion. What do you folk think?

Code change to ann-benchmarks/plotting/utils.py:
```
def generate_n_colors(n):
    vs = numpy.linspace(0.3, 0.9, 7)
```

Defaults:
![image](https://user-images.githubusercontent.com/35026793/100823467-38a16100-348f-11eb-84ae-91452c903b88.png)

Updates:
![image](https://user-images.githubusercontent.com/35026793/100823520-51aa1200-348f-11eb-9948-71565d21b7db.png)

**Comment by erikbern** [comment]
sure, feel free to submit a PR and I'll merge!
