### ISSUE TITLE
float32 vs float64

### ISSUE THREAD

**Issue by aaalgo** [erikbern/ann-benchmarks#20]
It appears that the benchmark has switched from float32 to float64 quite a while ago, and this somehow contributed to a substantial performance regression of KGraph, which is only optimized for float32 although float64 also runs.

Below are my justifications for using float32 in the context of approximate K-NN search:
- The search process is usually approximate, and the feature data are usually noisy by nature, so typically the precision of float64 is not necessary.
- The necessity of an index to speed up search presumes that data is big.  So a factor of 2x in the cost just to store the data in memory is significant.
- For some algorithm/implementation, using float32 means more data can be fit into cache and the code being much faster.

I believe the performance behavior of some library will be very different for float32 and float64 (though I believe the relative ranking of different libraries should roughly stay the same).  If only one can be chosen, I feel it should be float32 so that the benchmark represents the typical use case.  

Is there a particular reason to keep float64, or it's better supported by some libraries in the benchmark?
(There's another reason why KGraph is slow which I'm still investigating.)

**Comment by erikbern** [comment]
I didn't realize that we have switched to float64. Annoy uses only float32 for instance. If it's just a matter of setting `dtype=numpy.float32` then I can go ahead and fix that. I agree that float32 is more realistic since it's rarely useful to use 64 bit precision. In fact I even experimented a bit with float16 and float8 for Annoy to see if it would be even faster (it was not)

**Comment by aaalgo** [comment]
I checked the implementation all contenders, and found the following all use float32 internally: NMSLib, Falconn, Annoy, FLANN and KGraph.  NMSLib, Annoy and FLANN do automatic conversion on the C/C++ side.  Falconn and KGraph does explicit conversion in the benchmark code.  So I think the benchmark is totally fair and reasonable as far as the above methods are concerned.  

Among the remaining ones, I think the sklearn-based ones use float64 internally, but I'm not very sure.     RPForest uses float64 internally, and probably does not support automatic conversion from float32.  PANNS is implemented purely in python and uses numpy, and by default, the index is constructed with float32, as in the benchmark, but it is configurable.  NearPy also uses numpy, and computation is done in the type that is passed in, so it should be float64 in the benchmark.

It appears to me that the overhead of type conversion is minimal.  I think it's OK to leave the choice of type to the library implementation.    I'm closing this issue.
