### ISSUE TITLE
index construction time plotting

### ISSUE THREAD

**Issue by aaalgo** [erikbern/ann-benchmarks#22]
I plotted index construction time using data saved in glove.txt and see a spread of almost 2 orders of magnitude (hnsw(nmslib) index construction might have been parallelized according to code).  I'm most interested in the performance of sw-graph vs hnsw.  It's very hard to say which one is better because one might be able to improve the search performance of sw-graph by building more aggressive indices.  I collaborated with Princeton folks on developing a hierarchical version of the algorithm behind KGraph and the results were negative.  Initially there was noticeable speedup at the same accuracy, but after carefully controlling index construction setup, the speedup was gone.

I also suggest that we establish a standard hardware configuration to run the benchmark.  Preferrably some type of AWS instance which can be easily reproduced.  I think something close to your current setup should be good.

![build](https://cloud.githubusercontent.com/assets/5427210/15939002/da24341e-2e43-11e6-9dbc-3944177274e7.png)
![throughput](https://cloud.githubusercontent.com/assets/5427210/15939003/da294b5c-2e43-11e6-940a-2b0b70c000a6.png)

**Comment by erikbern** [comment]
This is great – feel free to send me a PR and I can include those benchmarks in the README.

The standard right now is using a c2.xlarge on AWS. I think it could be interesting also to look at bigger data sets in which case we should use a machine type with more RAM

**Comment by erikbern** [comment]
Btw in the precision-performance I filter out any points that are not on the Pareto frontier (meaning there is another point that dominates it both in terms of precision and performance)

**Comment by aaalgo** [comment]
The construction time plot uses exactly the same Pareto frontier points. 

diff plot-time.py plot.py
51c51
<                 ys.append(t[-3]) #1.0 / t[-2])    # this is indexing time
---
>                 ys.append(1.0 / t[-2])

I don't see c2.xlarge instances on EC2.  They might be no longer available.

**Comment by erikbern** [comment]
Sorry I meant c4.2xlarge – it says that in the readme

**Comment by andrewluetgers** [comment]
@aaalgo heres my vote to see this re-run for latest results and incorporated via PR this is a valuable facet of performance that needs to be part of the discussion.
