### ISSUE TITLE
Question:   The difference between the memory of the container and the index process.

### ISSUE THREAD

**Issue by lajiyuan** [erikbern/ann-benchmarks#227]
I use the Scann algorithm in the ann-benchmarks framework to run my own data set, the size of the data set is 50M, and the startup command is:
```bash
python3 run.py --algorithm scann --dataset data-50M --batch --timeout 18000
```
Docker container information is:
```
Created container d04dcfa2d5: CPU limit 0-79, mem limit 530102299392, timeout 18000, command ['--dataset', 'data-50M', '--algorithm', 'scann', '--module', 'ann_benchmarks.algorithms.scann', '--constructor', 'Scann', '--runs', '5', '--count', '10', '--batch', '[2000, 0.2, 2, "dot_product"]', '[[1, 30]]', '[[2, 30]]', '[[4, 30]]', '[[8, 30]]', '[[30, 120]]', '[[35, 100]]', '[[40, 80]]', '[[45, 80]]', '[[50, 80]]', '[[55, 95]]', '[[60, 110]]', '[[65, 110]]', '[[75, 110]]', '[[90, 110]]', '[[110, 120]]', '[[130, 150]]', '[[150, 200]]', '[[170, 200]]', '[[200, 300]]', '[[220, 500]]', '[[250, 500]]', '[[310, 300]]', '[[400, 300]]', '[[500, 500]]', '[[800, 1000]]']
```
After the program is finished running, I use grafana to check the container memory. The peak memory is 238G.
![image](https://user-images.githubusercontent.com/38530078/112310313-654be380-8cdf-11eb-9f00-9fb0d7eeadec.png)

 From the standard output log, the memory used by the indexing process is 54141892.0K ~ 54G. 
![image](https://user-images.githubusercontent.com/38530078/112309982-fff7f280-8cde-11eb-80f8-b03539cc75c9.png)

Why is there such a big gap?

**Comment by maumueller** [comment]
The way we measure memory is to just take a snapshot before and after indexing. I think this is probably the last spike from 186 to 233gb that you see. There are other parts that we don't measure, for example the pure size of the dataset and copies of that, which might be the first spikes that you get?

**Comment by lajiyuan** [comment]
Thank you for responding so quickly, I understand.
