### ISSUE TITLE
How do you know the interface of faiss python?

### ISSUE THREAD

**Issue by Kun-Ming** [erikbern/ann-benchmarks#231]
I want to add some faiss algorithms on this project, but I can't find description of faiss python interface. How do you get these information?

**Comment by maumueller** [comment]
I am not completely sure what you mean, but you can just take a look how we implemented IVF/LSH/HNSW in https://github.com/erikbern/ann-benchmarks/tree/master/ann_benchmarks/algorithms. I've implemented these following https://github.com/facebookresearch/faiss/wiki/Faiss-indexes if I remember correctly.

**Comment by Kun-Ming** [comment]
> I am not completely sure what you mean, but you can just take a look how we implemented IVF/LSH/HNSW in https://github.com/erikbern/ann-benchmarks/tree/master/ann_benchmarks/algorithms. I've implemented these following https://github.com/facebookresearch/faiss/wiki/Faiss-indexes if I remember correctly.

I had seen IVF/LSH/HNSW, they are fantastic implementation. I just wondering how do you know the argument of faiss function, such as search(), is that same as c++?

**Comment by maumueller** [comment]
I think I took it from the examples the pasted on the wiki. You can always take a look at https://github.com/facebookresearch/faiss/blob/master/faiss/python/__init__.py, or just do `help(...)` on the index object to see its methods.

**Comment by Kun-Ming** [comment]
> I think I took it from the examples the pasted on the wiki. You can always take a look at https://github.com/facebookresearch/faiss/blob/master/faiss/python/__init__.py, or just do `help(...)` on the index object to see its methods.

Thanks! That solved my question.
