### ISSUE TITLE
big-ann-benchmarks.com

### ISSUE THREAD

**Issue by erikbern** [erikbern/ann-benchmarks#241]
Just saw http://big-ann-benchmarks.com

I'm a bit surprised the authors of that competition didn't mention anything to me or the other people working on this benchmark suite? Feels like there's a lot of overlap and I wish we could have worked together on it.

cc @maumueller

**Comment by erikbern** [comment]
Actually just realized @maumueller is in the list of organizers... are you involved? Curious about your thoughts on whether it could be merged into this repo. I think there's a lot of value in having reproducible containers and everything open source.

**Comment by erikbern** [comment]
Sorry I must have missed that email or forgotten about it. Looking forward to see the code, hopefully there's an opportunity to collaborate!

**Comment by DmitryKey** [comment]
hello! Is there some progress on releasing the new framework? Specifically I'm interested to see the I/O libraries to handle loading of 100M or 1B vectors. When using for instance HNSW directly (code taken from the creators of it), data load becomes a bottlneck -- and this is not an issue of HNSW, but more a pure I/O slowness. I've been using this code implemented by Yandex (as part of open sourcing their 1B dataset): https://github.com/DmitryKey/bert-solr-search/blob/feature/hnswlib/src/util/utils.py#L57

**Comment by maumueller** [comment]
We are in the final phase, so hopefully the framework will be released in a week or two. We memory-map binary files, roughly like https://github.com/facebookresearch/faiss/blob/master/contrib/datasets.py#L194-L199.

**Comment by DmitryKey** [comment]
sounds great! Looking forward to test it.
