### ISSUE TITLE
Regarding a clarification

### ISSUE THREAD

**Issue by sayakpaul** [erikbern/ann-benchmarks#249]
From the [site](https://awesomeopensource.com/project/erikbern/ann-benchmarks):

> Note that we consider that set similarity datasets are sparse and thus we pass a sorted array of integers to algorithms to represent the set of each user.

Could you expand a bit more on this preferably with a small example w.r.t any of the benchmarking datasets provided? What is sorted and how exactly it is sorted?

**Comment by maumueller** [comment]
Hi @sayakpaul 

It means that three sets `[{1,3,2}, {1,3}, {1,5}]` are represented by the array `[1,2,3,1,3,1,5]` with an accompanying `size` attribute that would be `[3,2,2]`. See https://github.com/erikbern/ann-benchmarks/blob/18ba39b6a4af1243b26bf5fedc6c5c7ced791d70/ann_benchmarks/distance.py#L38-L45 for details.

**Comment by sayakpaul** [comment]
Thanks much. Appreciate it.
