### ISSUE TITLE
benchmark running for too long

### ISSUE THREAD

**Issue by aaalgo** [erikbern/ann-benchmarks#25]
I've been running the benchmark on a machine that shouldn't be much slower than c4.2xlarge (core i7-2600k @ 3.4GHz).  It's been 5 days and I only see 195 lines in sift.txt (the plot looks good though).  There are 321 lines in the standard glove.txt, and 82 lines in the standard sift.txt which I think is incomplete.  So I estimate it will take 15 - 20 days for me to finish running everything.  Is it supposed to be so?

I'm attaching the SIFT plot I produced with the data I have so far, which is coherent to the Glove plot I see from the project page.  (KGraph bug fixed.)

![xx](https://cloud.githubusercontent.com/assets/5427210/16066621/e962de4c-3282-11e6-8b7c-e2e6b8abeb2b.png)

**Comment by erikbern** [comment]
i think i takes something like 5-7 days to run everything

you don't have to delete some results though – nearpy, lshf, panns etc haven't changed much

good to see that kgraph is back!

**Comment by searchivarius** [comment]
@aaalgo please, uncomment the line where SW-graph and HNSW save indices. This will make things faster.

**Comment by aaalgo** [comment]
Is there any reason to disable saving index on disk?  I thought I was following NMSLib's example to save the index, but didn't realize the saving's actually disabled by a comment.  I think without saving index, the computation time has become almost impractical to me.

**Comment by searchivarius** [comment]
@aaalgo I think @erikbern had some problems with disk space.

**Comment by aaalgo** [comment]
That's legitimate.  I'll leave @erikbern to decide whether or not to comment out the line for KGraph:
https://github.com/erikbern/ann-benchmarks/blob/master/ann_benchmarks/__init__.py#L238

**Comment by searchivarius** [comment]
@aaalgo now, I made the benchmark save indices by default (for nmslib & kgraph). One should be able to cancel saving by --no_save_index

**Comment by aaalgo** [comment]
I think saving index is a good enough solution.
