### ISSUE TITLE
ERROR - Child process for container raised exception 137 : Annoy

### ISSUE THREAD

**Issue by PratyushGoel** [erikbern/ann-benchmarks#257]
Using Python v3.6.10
Followed all the instructions of readme.

Command `python run.py --dataset glove-25-angular --docker-tag ann-benchmarks-nmslib` worked perfectly and generated the ouput graph for nmslib on glove-25-angular dataset.

While running Annoy on dataset glove-25-angular using command `python run.py --dataset glove-25-angular --docker-tag ann-benchmarks-annoy` I get error
ERROR - Child process for container dd46e7851b raised exception 137
What could be the reason?

The install status for annoy was 'success'

**Comment by maumueller** [comment]
How much RAM do you have available on your setup? It could run OOM.

**Comment by PratyushGoel** [comment]
I am using mac with 16gb memory. 

You are right ! The docker preferences was set to 4 GB of RAM only. Maybe, thats why the error was occuring.
Increasing it to 16GB seems to be working. 

Thanks for the help !
