### ISSUE TITLE
what's the physical memory limit ?

### ISSUE THREAD

**Issue by 2492202119** [erikbern/ann-benchmarks#261]
hi,  do we have minimum memory limit for ann workload ?
  we run ann workload with "python3 run.py --dataset gist-960-euclidean --algorithm kgraph --force --runs 1 --count 10" and use cgroup to limit its physical memory 60% of peak memory. we found swapfile hang, ann thread becomes zombie, cpu is 100%. we must reboot our machine.

**Comment by maumueller** [comment]
For GIST I was experiencing that you need around 16 GB of RAM to carry out all the implementations.

**Comment by 2492202119** [comment]
we are doing experiment to test physical memory to swapfile ratio. we keep total memory equals peak memory. but we tune the ratio of physical memory and try to find the minimal physical memory demand with enough swapfile
