### ISSUE TITLE
question about metric of recall at K used on the paper

### ISSUE THREAD

**Issue by shin285** [erikbern/ann-benchmarks#263]
I saw recall at k in the ann-benchmarks paper. When I look at the formula, it looks like the same formula as precision at k, but it is expressed as recall at k. Is there any reason why it is expressed as recall rather than precision?

**Comment by shin285** [comment]
Thanks for the quick reply! I will close this issue. Thank you.

**Comment by zhiqihuang** [comment]
I came across this recall metric problem recently. I'm wondering what if k is larger than #positives for some queries, the recall defined in the paper can never be 1.0
