### ISSUE TITLE
Which parameters were used for your published results?

### ISSUE THREAD

**Issue by Gian-Alessio** [erikbern/ann-benchmarks#275]
Hey! 

Is there a way to know which parameters were used for your published results? I noticed that in the algos.yaml some approaches like n2 have multiple parameter. Which one lead to the best results using SIFT-128 for example?

**Comment by erikbern** [comment]
We just run all of them and then remove the results that aren't on the "efficient frontier". We don't track which parameter was the best – different parameter combinations may win at different parts of the tradeoff curve

**Comment by maumueller** [comment]
@Gian-Alessio: You can read off this information from the interactive plots. See http://ann-benchmarks.com/glove-100-angular_10_angular.html as an example.
