### ISSUE TITLE
python install.py error

### ISSUE THREAD

**Issue by miaohenshuai** [erikbern/ann-benchmarks#276]
hi, when i exe 'python install.py', how to fix it?

```
logs:
------
Building ngt...
[+] Building 4.1s (4/4) FINISHED
 => [internal] load build definition from Dockerfile.ngt                     0.0s
 => => transferring dockerfile: 554B                                         0.0s
 => [internal] load .dockerignore                                            0.0s
 => => transferring context: 34B                                             0.0s
 => ERROR [internal] load metadata for docker.io/library/ann-benchmarks:lat  4.0s
 => [auth] library/ann-benchmarks:pull token for registry-1.docker.io        0.0s
------
 > [internal] load metadata for docker.io/library/ann-benchmarks:latest:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

**Comment by maumueller** [comment]
Does this only happen for NGT and other implementations succeed? It seems that it tries to pull `ann-benchmarks:latest`, but that image should have been built locally as the first step of running `python install.py`.

**Comment by miaohenshuai** [comment]
yeap, other implementations are all failed, how should i fix it.

**Comment by maumueller** [comment]
Could you share the whole log produced from running `python3 install.py --algorithm annoy`?

**Comment by miaohenshuai** [comment]
➜ python3 install.py --algorithm annoy
Building base image...
[+] Building 3.1s (13/13) FINISHED
 => [internal] load build definition from Dockerfile                         0.0s
 => => transferring dockerfile: 337B                                         0.0s
 => [internal] load .dockerignore                                            0.0s
 => => transferring context: 34B                                             0.0s
 => [internal] load metadata for docker.io/library/ubuntu:18.04              3.0s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                0.0s
 => [1/7] FROM docker.io/library/ubuntu:18.04@sha256:0fedbd5bd9fb72089c7bbc  0.0s
 => [internal] load build context                                            0.0s
 => => transferring context: 256B                                            0.0s
 => CACHED [2/7] RUN apt-get update                                          0.0s
 => CACHED [3/7] RUN apt-get install -y python3-numpy python3-scipy python3  0.0s
 => CACHED [4/7] RUN pip3 install -U pip                                     0.0s
 => CACHED [5/7] WORKDIR /home/app                                           0.0s
 => CACHED [6/7] COPY requirements.txt run_algorithm.py ./                   0.0s
 => CACHED [7/7] RUN pip3 install -r requirements.txt                        0.0s
 => exporting to image                                                       0.0s
 => => exporting layers                                                      0.0s
 => => writing image sha256:f09f313a67005ce47777f46e17312d1d35c6137a92be4b6  0.0s
 => => naming to docker.io/library/ann-benchmarks                            0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Building algorithm images... with (1) processes
Building annoy...
[+] Building 2.8s (4/4) FINISHED
 => [internal] load build definition from Dockerfile.annoy                   0.0s
 => => transferring dockerfile: 189B                                         0.0s
 => [internal] load .dockerignore                                            0.0s
 => => transferring context: 34B                                             0.0s
 => ERROR [internal] load metadata for docker.io/library/ann-benchmarks:lat  2.7s
 => [auth] library/ann-benchmarks:pull token for registry-1.docker.io        0.0s
------
 > [internal] load metadata for docker.io/library/ann-benchmarks:latest:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed


Install Status:
{'annoy': 'fail'}
