### ISSUE TITLE
Format of dataset, queries and output

### ISSUE THREAD

**Issue by corneliusschroeder** [erikbern/ann-benchmarks#287]
Hello,
I'm trying to include my own algorithm to benchmark it. However, I'm not sure in which format (type and shape) the dataset, single and batch queries are supplied to the algorithms. In which format should the algorithm return the result? As a list of the indices of the nearest neighbors?
Thanks for your help!

**Comment by erikbern** [comment]
There's plenty of examples if you look under https://github.com/erikbern/ann-benchmarks/tree/master/ann_benchmarks/algorithms
