### ISSUE TITLE
Evaluate Elasticsearch approximate kNN API

### ISSUE THREAD

**Issue by rw-access** [erikbern/ann-benchmarks#298]
This was recently released in Elasticsearch 8.0+ and the API is documented [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search-api.html)

Elasticsearch is distinct in both implementation and product from OpenSearch (Amazon maintained fork), and I expect that the two APIs will have different results. Both are HNSW based.

Thanks for maintaining this repo!

**Comment by erikbern** [comment]
Feel free to submit a pull request!
