### ISSUE TITLE
Wrong x-axis label values (recall) in README

### ISSUE THREAD

**Issue by marcjulianschwarz** [erikbern/ann-benchmarks#299]
I just went through the ann-benchmarks [paper](https://arxiv.org/pdf/1807.05614.pdf). Now I am wondering whether the values on the x-axis in the README plots should be reversed, going from zero to one and not from one to zero. All figures in the paper (and on ann-benchmarks.com) have x-values going from zero to one with a high number of queries per second when recall is closer to zero.

Shouldn't the recall value be low when there are lots of queries per second and higher when there are less queries per second?

**Comment by maumueller** [comment]
Hi Marc, 

I find the logit-scale a bit difficult to read as well, but they seem correct to me. The `x` values are going from 0 to 1, the values close to one are just written as 1-10^-1 (0.9),1-10^{-2} (0.99), ...

**Comment by marcjulianschwarz** [comment]
Hi @maumueller,

sure that makes sense. Didn't see the `1-` there, thanks for pointing that out.
Guess this issue can now be seen as feedback, from what I can tell this scale isn't used elsewhere with ann-benchmarks which makes it confusing.
