### ISSUE TITLE
More/better Algorithm implementation documentation

### ISSUE THREAD

**Issue by kchalkSGS** [erikbern/ann-benchmarks#320]
I see that elastic search and solr both use hnsw algorithms. I see that there are 4 hnsw algorithms on the website. I see that there are elastic search specific implementations in the code base, but I can't tell which of the 4 hnsw algorithms is used by either db. I also happen to know that SCANN is a google algrothim and annoy is from spotify, but those details are not on the site. 

It would be very helpful to be to know how algorithms relate to companies or database implementations. Perhaps a section could be added to the algorithm page citing the paper the algorithm was defined in and/or the library versions used to run tests?

**Comment by erikbern** [comment]
There is a ton of configuration going into each algorithm, so it's not always trivial to summarize. I think the easiest is actually to just look in the configuration – in particular the [algos.yaml file](https://github.com/erikbern/ann-benchmarks/blob/master/algos.yaml). Hope that makes sense!
