### ISSUE TITLE
Does the ann-benchmarks homepage have plans to update the data?

### ISSUE THREAD

**Issue by wangting0128** [erikbern/ann-benchmarks#329]
Hello, the data on the ann-benchmarks homepage is already two years ago. I would like to ask if there is any plan to update the data in the near future?
Our Milvus database has been upgraded to the V2.* version, if the data will be updated, we are happy to update our code to the latest version.
Looking forward to your reply, thank you very much!

**Comment by maumueller** [comment]
@erikbern: What do you think? I agree that it's about time to re-run the benchmark.

**Comment by erikbern** [comment]
Yeah agree. Let me do it! I'll use the latest code in the repo, so @wangting0128 feel free to update the Milvus code if you want me to use the latest. I can do some quick sanity check that we're not too far behind the latest version on other ones too.

**Comment by wangting0128** [comment]
@erikbern @maumueller

**Comment by wangting0128** [comment]
Hi, I still have a few questions I would like to ask.

1. What scenarios will the re-run benchmark mainly cover, in addition to those shown in [ann-benchmarks.com](http://ann-benchmarks.com/index.html)
2. Will new server deployment scenarios be added? Similar to distributed server, we are interested in this

Looking forward to your reply, thank you very much

**Comment by erikbern** [comment]
I'm just planning to run the benchmarks as they are in a repo – you can take a look at algos.yml to see.

**Comment by wangting0128** [comment]
Milvus updated version: https://github.com/erikbern/ann-benchmarks/pull/333
Please help me review, if there is any need to modify, please let me know, thanks a lot.

**Comment by erikbern** [comment]
Great! I'm planning to go through all algos in the next couple of weeks

**Comment by erikbern** [comment]
I'll probably run two rounds with a few weeks in between, just in case there's any issues with the benchmarks.

**Comment by karlkovaciny** [comment]
pgvector is mentioned in the readme but not in any of the results, so I hope to see them in the next run.

**Comment by erikbern** [comment]
Currently running it – will be updating the stats in the next few days!

**Comment by imaurer** [comment]
Will it include updates to Pgvector?

**Comment by erikbern** [comment]
I updated the charts in the repo yesterday but haven't updated the website yet. Planning to do that in a few days!

**Comment by ramialt** [comment]
Bump to please update the charts. They are so much more readable when they are interactive graphs on the website and I can filter out algorithms to only the few in consideration

**Comment by erikbern** [comment]
The website has the latest data now!
