### ISSUE TITLE
Split up building and query parameters

### ISSUE THREAD

**Issue by maumueller** [erikbern/ann-benchmarks#41]
Currently, we spend a lot of time basically building the same data structure over and over again. What we could do instead, is split up _build_ and _query_ parameters. For example, Annoy is currently configured by

```
    annoy:
      constructor: Annoy
      base-args: ["@metric"]
      run-groups:
        annoy:
          args: [[100, 200, 400], [100, 200, 400, 1000, 2000, 4000, 10000,
                20000, 40000, 100000, 200000, 400000]] # number of trees x number of points to gather
```

It would save a lot of time, if one were to separate query and build parameters in the following way: 
```
    annoy:
      constructor: Annoy
      base-args: ["@metric"]
      run-groups:
        annoy:
          build-args: [[100, 200, 400]] # number of trees 
          query-args: [[100, 200, 400, 1000, 2000, 4000, 10000,
                20000, 40000, 100000, 200000, 400000]] # number of points to gather during query
```
The idea would now be to build the data structure for each `build-args` group, and query it for all (combinations of) `query-args`. This should be rather straight-forward to do.

Should be labeled as "enhancement".

**Comment by erikbern** [comment]
i like the idea – actually thought about something similar too. would help with the slow nmslib index building time as well

**Comment by maumueller** [comment]
This has been added, closing.
