### ISSUE TITLE
Installation of Milvus

### ISSUE THREAD

**Issue by kimihailv** [erikbern/ann-benchmarks#421]
When I try to build the image for Milvus, the following error occurs:

`Step 6/7 : RUN python3 -c 'import pyknowhere'
 ---> Running in e84180a73171
Illegal instruction (core dumped)
The command '/bin/sh -c python3 -c 'import pyknowhere'' returned a non-zero code: 132`

**Comment by erikbern** [comment]
are you running on an x86?

**Comment by HungryFour** [comment]
Also encountered this problem.
```
Python 3.10.6
```
```
Linux version 3.10.0-1160.71.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)) #1 SMP Tue Jun 28 15:37:28 UTC 2022
```

**Comment by hhy3** [comment]
It's supposed to be run on an AVX supported machine.

**Comment by HungryFour** [comment]
@hhy3   It's supposed  AVX.
![image](https://github.com/erikbern/ann-benchmarks/assets/8122332/4c5a50f4-e6d4-4d1d-bf3d-61d0c97e9d5f)

**Comment by kimihailv** [comment]
> are you running on an x86?

yes

**Comment by yuzhenmao** [comment]
same issue here

**Comment by aosh-ab7e** [comment]
I'm wondering if changing the base image from `milvusdb/knowhere-env` to `milvusdb/milvus` might work.
(I've only glanced at it, but `milvusdb/knowhere-env` seems quite internal and is known only by zilliz employees)

**Comment by HungryFour** [comment]
https://github.com/milvus-io/knowhere.  knowhere need to install

**Comment by pauldintel** [comment]
can anyone able to connect to Milvus server from ann benchmark client ? I don't see connection specification exist inside the module.py file ?

**Comment by Coderik** [comment]
> can anyone able to connect to Milvus server from ann benchmark client ? I don't see connection specification exist inside the module.py file ?

The benchmark does not evaluate Milvus as a complete engine, only [Knowhere](https://github.com/zilliztech/Knowhere) - a library written in C++ that acts as Milvus's internal core. So, there is no connection (see [ann_benchmarks/algorithms/milvus/module.py](https://github.com/erikbern/ann-benchmarks/blob/main/ann_benchmarks/algorithms/milvus/module.py))

**Comment by haorenfsa** [comment]
It also requires avx-512 for the latest version. Environment Checklist for Milvus on Kubernetes Milvus documentation https://milvus.io/docs/prerequisite-helm.md

For cloud provider, you're gonna need Cascade Lake or newer series. Take AWS  as example. You'll need at least the 6th generation of

**Comment by PRIYANSHU2026** [comment]
it is supported in python 3.10

**Comment by zjx1230** [comment]
> When I try to build the image for Milvus, the following error occurs:
> 
> `Step 6/7 : RUN python3 -c 'import pyknowhere' ---> Running in e84180a73171 Illegal instruction (core dumped) The command '/bin/sh -c python3 -c 'import pyknowhere'' returned a non-zero code: 132`

Has this issue been resolved?

**Comment by maumueller** [comment]
As @haorenfsa pointed out, it requires a machine supporting avx-512.
