### ISSUE TITLE
What's the exact instance type for benchmarks?

### ISSUE THREAD

**Issue by alexklibisz** [erikbern/ann-benchmarks#426]
I'd like to reproduce some of the benchmarks. The readme says "r6.16xlarge", but there are a few flavors of r6: r6g, r6i, r6in, r6a (https://aws.amazon.com/ec2/instance-types/). @erikbern Do you remember precisely which one of these you used? Thanks!

**Comment by erikbern** [comment]
Pretty sure it's r6i.x16xlarge – i stands for intel, since benchmarks aren't supported on ARM at this point
