### ISSUE TITLE
Add FLASH

### ISSUE THREAD

**Issue by irachex** [erikbern/ann-benchmarks#46]
https://github.com/RUSH-LAB/Flash

https://arxiv.org/pdf/1709.01190.pdf

<img width="557" alt="screen shot 2017-12-26 at 03 41 38" src="https://user-images.githubusercontent.com/596262/34342645-3aff0e98-e9f1-11e7-812e-f2397f22abfb.png">

**Comment by erikbern** [comment]
Looks like it's more for sparse vectors?

**Comment by maumueller** [comment]
I actually contacted the authors of Flash earlier this year. They confirmed that their algorithm is tuned for much sparser datasets and probably won‘t perform well in our benchmark. 

Furthermore, they will contact us if the have some python wrapper that we can easily use.
