### ISSUE TITLE
Milvus algorithm couldn't find the connection options inside ../ann_benchmarks/algorithms/milvus

### ISSUE THREAD

**Issue by pauldintel** [erikbern/ann-benchmarks#467]
hi , 
I couldn't find how to add connections options under module.py or config.yaml .
I have ann benchmark in one node and vector db (milvus) in different host . 

While looking at this : https://milvus.io/docs/example_code.md
I am looking for a connection entry inside ANN benchmark for milvus but couldn't locate how to connect remotely to the vector DB server node . any help ?

connections.connect("default", host="localhost", port="19530")

**Comment by maumueller** [comment]
@wangting0128 added the Milvus implementation, so he probably knows best. 

As far as I understand, the version that is used here is not using a client/server architecture.

**Comment by pauldintel** [comment]
if that is the case then I need to know how and which setup on the ANN benchmark code I should be using as client connecting to any Vector DB server please ? thanks !

**Comment by maumueller** [comment]
You can find one example here: https://github.com/erikbern/ann-benchmarks/tree/main/ann_benchmarks/algorithms/elasticsearch The dockerfile takes care of starting the server, the connections are made inside `module.py`.

**Comment by pauldintel** [comment]
hi thanks . Elasticseach has the connection entry but Milvus doesn't . Could you please help adding them ? https://github.com/erikbern/ann-benchmarks/tree/main/ann_benchmarks/algorithms/milvus

I can't see it inside module.py

**Comment by pauldintel** [comment]
I would appreciate NOT to close the issue until addressed : "Milvus algorithm couldn't find the connection options" inside module.py

**Comment by pauldintel** [comment]
@wangting0128  do you know why I am getting below exceptions ? 

~/ann-benchmarks$ sudo python3 run.py --dataset glove-25-angular --algorithm milvus --runs=1
2023-09-29 22:37:12,919 - annb - INFO - running only milvus
Traceback (most recent call last):
  File "/home/ubuntu/ann-benchmarks/run.py", line 7, in <module>
    main()
  File "/home/ubuntu/ann-benchmarks/ann_benchmarks/main.py", line 341, in main
    raise Exception("Nothing to run")
Exception: Nothing to run
