### ISSUE TITLE
[Dataset] The train and test sections of some datasets have only 1 dimension for each row

### ISSUE THREAD

**Issue by zlwu92** [erikbern/ann-benchmarks#474]
Hi,

I try to read data from the hdf5 input dataset, I found for `Kosarak` and `[MovieLens-10M]`, they have only 1 element for each row? Is there any problem with these datasets?
![image](https://github.com/erikbern/ann-benchmarks/assets/104770161/194a6b2a-7eda-4c24-95c0-c3d40affb3f7)

**Comment by maumueller** [comment]
These datasets are sparse and use somewhat like the scipy csr format for packing them efficiently. Please see https://github.com/erikbern/ann-benchmarks/blob/main/ann_benchmarks/distance.py#L104 as an example of how you can work with them.

**Comment by zlwu92** [comment]
So, when I use this distance function to get train and test objects which are basically list object, right? np.ndarray.

Then I found that len of each row is not the same, so it still stored in compact style, right?

I guess that does each element in the rows represents the index of the non-zero element in the orignal sparse vector?

```
f = h5py.File(h5_file, 'r')
train, test = dataset_transform(f)
print(type(train))
print(len(train))
for i in train[0]:
      print(str(i), end=' ')
print()
```
![image](https://github.com/erikbern/ann-benchmarks/assets/104770161/5b64d486-3fa7-48d9-afc9-37757ec3498f)

**Comment by maumueller** [comment]
Yes, `train[0]` is the first sparse vector, it has 123 non-zeros, at the positions listed in your example.
