### ISSUE TITLE
looking for the results data

### ISSUE THREAD

**Issue by juanKersul** [erikbern/ann-benchmarks#480]
I'm developing my own implementation of a knn search algorithm, and  I'm trying to compare with the other implementations . 
However, my hardware is very limited so I'm having a hard time trying to replicate your results. I was wondering if I could get the results data (the once are stored in /results) so I can make the comparison. If so, I appreciate if you could provide a link to it.
Thanks in advance

**Comment by frg01** [comment]
why you want replicate author's result ,I mean ,it's just a reference result for us. You can run all algorithm on you machine.  Or ,you can see offical result in https://ann-benchmarks.com/;
