### ISSUE TITLE
Wrong result in using FASHION-Mnist

### ISSUE THREAD

**Issue by mithunputhusseri** [erikbern/ann-benchmarks#481]
Hi Team,

I am testing postgres:pgvector vector database. I am running fashionmnist dataset. At the 1753rd vector in test, the nearest neighbour algorithms is giving me wrong result.

From db: {6349,35759,28985,6773,47304,20541,42928,1917,37047,25325,29116,59764,47933,2860,54623,55051,27275,52975,17235,25513,55102,12008,49533,46245,26659,53822,38326,4236,27257,3023,52362,4253,46072,48465,59565,58853,33506,12176,8910,53075,30478,50572,615,24559,21951,50392,41150,35174,55308,40291,17818,58653,578,16808,47401,36499,24629,21902,41678,46517,11300,29654,31262,1689,20176,13866,54595,53476,54953,3835,32542,40057,16698,25292,58483,40747,7271,20580,51551,45222,14984,37766,11633,49348,49519,35873,46319,23766,35257,57740,4595,36427,14214,38592,27046,43771,35610,54373,25315,**2583**}

Actual: {6349,35759,28985,6773,47304,20541,42928,1917,37047,25325,29116,59764,47933,2860,54623,55051,27275,52975,17235,25513,55102,12008,49533,46245,26659,53822,38326,4236,27257,3023,52362,4253,46072,48465,59565,58853,33506,12176,8910,53075,30478,50572,615,24559,21951,50392,41150,35174,55308,40291,17818,58653,578,16808,47401,36499,24629,21902,41678,46517,11300,29654,31262,1689,20176,13866,54595,53476,54953,3835,32542,40057,16698,25292,58483,40747,7271,20580,51551,45222,14984,37766,11633,49348,49519,35873,46319,23766,35257,57740,4595,36427,14214,38592,27046,43771,35610,54373,25315,**32897**}

You can see the result differ at the last value. Is this expected

Thanks,
Mithun

**Comment by erikbern** [comment]
pgvector is approximate and not guaranteed to return the correct nearest neighbors
