### ISSUE TITLE
time consumed by run.py

### ISSUE THREAD

**Issue by dipshirajput** [erikbern/ann-benchmarks#492]
Hi all,

please let me know how much time it takes for run.py code to finish the execution ?

Thanks.

**Comment by erikbern** [comment]
For all the benchmarks? It should take a few days to run all of them

**Comment by dipshirajput** [comment]
@erikbern 
i ran the run.py day before yesterday. it has reached upto the logs as shown in screenshot.
please give some clarity that how much time it might take more to complete the execution ? and how can we see/analyse which DB is performing better ?
![Screenshot from 2024-03-07 10-32-58](https://github.com/erikbern/ann-benchmarks/assets/52161957/6f680800-eb4d-4057-9156-da2ab909b3d3)


Thanks in advance.
