### ISSUE TITLE
@erikbern

### ISSUE THREAD

**Issue by dipshirajput** [erikbern/ann-benchmarks#493]
@erikbern 
i ran the run.py day before yesterday. it has reached upto the logs as shown in screenshot.
please give some clarity that how much time it might take more to complete the execution ? and how can we see/analyse which DB is performing better ?
![Screenshot from 2024-03-07 10-32-58](https://github.com/erikbern/ann-benchmarks/assets/52161957/6f680800-eb4d-4057-9156-da2ab909b3d3)

Thanks in advance.

_Originally posted by @dipshirajput in https://github.com/erikbern/ann-benchmarks/issues/492#issuecomment-1982359858_

**Comment by erikbern** [comment]
It's going to take several days to run it. You need to create plots afterwards!

**Comment by dipshirajput** [comment]
ok. several days any approximation ? @erikbern
