### ISSUE TITLE
db running before running the benchmark

### ISSUE THREAD

**Issue by dipshirajput** [erikbern/ann-benchmarks#495]
HI @erikbern ,
do we need to run the databases seperately before following the steps in the doc for running the benchmark? i mean the steps mentioned in this repo are only responsible for running the benchmark or it runs the databases also ?

**Comment by maumueller** [comment]
The contributors of the specific implementation made sure that it installs and runs the database. Note that some implementations like milvus have a standalone version for this benchmark that avoids the client/server architecture.
