### ISSUE TITLE
Consistently prewarming database

### ISSUE THREAD

**Issue by wahajali** [erikbern/ann-benchmarks#500]
pg_embedding client currently does pre-warming of database while the same is not happening in other databases, including pgvector. Does this effect the comparision in terms of QPS? And should this be standardized across the board?

**Comment by ankane** [comment]
Hi @wahajali, for pgvector specifically, the data should already be in shared buffers, so prewarming shouldn't make a difference.

**Comment by wahajali** [comment]
Hi @ankane could you please elaborate why that is the case? Does the shared_buffer get populated on insertion?

**Comment by ankane** [comment]
Yes, and when the index is created. You can run the benchmarks with and without `pg_prewarm` to compare.
