### ISSUE TITLE
benchmark stopped with exit code 0 

### ISSUE THREAD

**Issue by dipshirajput** [erikbern/ann-benchmarks#501]
@maumueller @erikbern  
Hi all,
while i was running the benchmark from 10days approx, it stopped with an exit code 0.
1. can you tell me if its the completion of benchmark performance run or there could be some issue ?
2. also, how can we analyse the results after graph plotting has been done ?

![remmina_10 168 1 45:1_10 168 1 45:1_2024325-62740 858156](https://github.com/erikbern/ann-benchmarks/assets/52161957/d1494443-e36a-4687-a650-19c7031662a0)

Thanks in advance .

**Comment by erikbern** [comment]
I think that means it's done!
