### ISSUE TITLE
Question about recall calculation

### ISSUE THREAD

**Issue by oleg0x** [erikbern/ann-benchmarks#519]
Hello,
Could you clarify please how recall is calculated in the case when an algorithm search returns 10 equal vectors each of which is the closest to the request? Is it possible that in such case the recall (from get_recall_values function?) will be 100%?

**Comment by maumueller** [comment]
We look at the distances of the reported points. Every point that is within the distance (+ small epsilon) of the k-th nearest neighbor is considered a correct result.

**Comment by oleg0x** [comment]
Suppose for k=10 an algorithm returns 10 copies of the same point which is the closest to a query. Will the recall be 100% or 10% in this case?

**Comment by maumueller** [comment]
Now I get what you mean. As far as I can see, we do not check whether an algorithm returns duplicated points. It would get 100% recall by just returning the nearest neighbor 10 times.

**Comment by oleg0x** [comment]
OK, thanks. But now it seems this is a loophole for ANNS algorithms developers :). If someone fix it, the results may change a little.
