### ISSUE TITLE
Incorrect Recall Rate with SIFT 50M Dataset in Ann-Benchmarks using PGVector IVF

### ISSUE THREAD

**Issue by HungryFour** [erikbern/ann-benchmarks#540]
Dear Ann-Benchmarks team,

I am currently attempting to test an algorithm using the SIFT 50M dataset from the following link: http://corpus-texmex.irisa.fr/. I have downloaded the Base set and Query set from the provided FTP links:

- Base set: ftp://ftp.irisa.fr/local/texmex/corpus/bigann_base.bvecs.gz
- Query set: ftp://ftp.irisa.fr/local/texmex/corpus/bigann_query.bvec

I have extracted the first 50 million entries from the Base set and combined them into an HDF5 file following the structure outlined in datasets.py's write_output function. However, when performing the recall calculation with the PGVector IVF, I am encountering an issue where the recall rate seems incorrect.

Could you please assist me in identifying potential causes for this discrepancy? I have ensured that the data preprocessing and the recall calculation steps are followed as per the guidelines.

I would appreciate any guidance or insights you could provide to resolve this issue.

Best regards

**Comment by HungryFour** [comment]
@erikbern  I really need your help. Please

**Comment by maumueller** [comment]
@HungryFour Please provide more details in which sense the recall seems wrong. I suppose it would be easiest to share the hdf5 files of a single result, the groundtruth nearest neighbors calculated by ann-benchmarks, and a script that shows your way of computing recall. 

Note that we compute recall not by comparing to the groundtruth labels, but rather look at the fraction of points that are within the k-NN distance of the groundtruth.

**Comment by HungryFour** [comment]
Thanks for the reply, the issue has been fixed. After reading the bvecs in Python, the query was not converted to numpy.float32, which led to a deviation in the distance calculation
