### ISSUE TITLE
Illegal instruction (core dumped) when importing vespa_ann_benchmark in Vespa container

### ISSUE THREAD

**Issue by MarsMan13** [erikbern/ann-benchmarks#556]
Firstly, the specification of my host system is as follows:

OS: RockyLinux 7
CPU: Intel(R) Xeon(R) CPU E5-2690

When I run the following command:

`python3 run.py --dataset nytimes-256-angular --algorithm 'hnsw(vespa)' --parallelism 1 --runs 3`
An error occurs.

Upon debugging, I discovered that the issue arises inside the Vespa container when attempting to import vespa_ann_benchmark (at `/ann_benchmarks/vespa/module.py:1`)
Specifically, the error message is: `Illegal instruction (core dumped)`

Could you provide guidance on resolving this issue?

Thank you!

**Comment by maumueller** [comment]
It seems that this requires a CPU that supports AVX-512. This is not in our hands, you will have to ask the vespa team directly.

**Comment by MarsMan13** [comment]
@maumueller 
Thank you for your helpful answer!
