### ISSUE TITLE
pynndescent

### ISSUE THREAD

**Issue by erikbern** [erikbern/ann-benchmarks#59]
saw this randomly: https://github.com/lmcinnes/pynndescent

**Comment by maumueller** [comment]
Sounds interesting, https://github.com/lmcinnes/pynndescent/issues/2.

**Comment by erikbern** [comment]
nice – thanks for reaching out to the author!

**Comment by erikbern** [comment]
closing since https://github.com/erikbern/ann-benchmarks/pull/67
