### ISSUE TITLE
Remove FALCONN from benchmarks

### ISSUE THREAD

**Issue by ilyaraz** [erikbern/ann-benchmarks#61]
Please, remove FALCONN from the benchmarks. It's not properly tuned for the new settings (100 neighbors instead of 10 etc), and the results are confusing.

We might later add it back (the new, faster version), but meanwhile I don't want the results to be here.

**Comment by erikbern** [comment]
Can you submit a pull request? Thanks

**Comment by ilyaraz** [comment]
There is no way for me to do that without re-running everything, since it does not seem like the numerical results are available.

**Comment by erikbern** [comment]
I will re-run the results in a couple of weeks, so feel free to make any changes (eg disabling FALCONN) until then. Unfortunately I also don't have the results available anymore
