### ISSUE TITLE
New run May 2018

### ISSUE THREAD

**Issue by erikbern** [erikbern/ann-benchmarks#81]
Have been running it on a c5.4xlarge for about 36h. It's still on glove-100-angular and it's mostly done:

![image](https://user-images.githubusercontent.com/1027979/40232816-58d44558-5a6e-11e8-8980-0a7fa04aa454.png)

Not sure what's up with NGT... think maybe it timed out and we should increase timeout a bit. Especially since we're now running many searches in the same container and CPU is limited to 1. I'll double it from 2h to 4h I think.

**Comment by yurymalkov** [comment]
Hm...  It seems that kgraph and nmslib also didn't pass the time limit. I am not sure that 4h limit would be enough. Building a high quality nmslib hnsw index may take an hour on a 6-core machine. So probably it may take 5 hours on a single core.

**Comment by erikbern** [comment]
I'll start with 4h and will increase it further if it's not enough. c5.4xlarge are pretty fast machines

**Comment by yurymalkov** [comment]
Cool! 
Will there be a simple way to see what indexes failed to build in 4 hours?

**Comment by erikbern** [comment]
yeah will get that for you later

**Comment by masajiro** [comment]
The NGT construction was adjusted for many cores. I'll provide NGT for single core.

**Comment by erikbern** [comment]
Here's the latest numbers:

![image](https://user-images.githubusercontent.com/1027979/40521895-e755494e-5f9b-11e8-8489-39baeecf2283.png)

This took almost a week to run... the problem is that there's so many algorithms now. The plot above is almost 600 different runs vs I think it used to be around 150. I just removed a lot of combinations from algos.yml and will rerun

**Comment by yurymalkov** [comment]
@erikbern Thanks! I would note that hnsw query time runs are pretty cheap (you can tell it just by looking at the graph), removing them should not save much time.

**Comment by maumueller** [comment]
Does it make sense to keep both hnswlib and hnsw(nmslib) running? They seem perform rather identical.

@erikbern You could also plot with `--raw` or use `create_website.py` with the `--scatter` option to get a better impression of which parameter configurations can be removed.

**Comment by yurymalkov** [comment]
@maumueller hnsw(nmslib) and hnswlib are different implementations with somewhat different functionality (i.e. exotic spaces+slightly faster at query time vs incremental index, less memory footprint and less build time). 
I am actually not sure if they perform that similar on other datasets.

**Comment by erikbern** [comment]
Np keeping both

**Comment by erikbern** [comment]
Closing this in favor of #82 which I'm merging now
