### ISSUE TITLE
Noob question: OS you used and requirements

### ISSUE THREAD

**Issue by richarmony** [erikbern/ann-benchmarks#89]
Hello @erikbern and team,

First of all, let me congratulate you for your fine job, it is amazing :D 

I'm trying to run your benchmark for K = 1 (seems like performance changes). I'm using Ubuntu 16.04 and python3.5.

While I was installing (sudo python3 install.py) I noticed it installs lots of dependencies from bionic beaver. Is Bionic Beaver (18.04) or any other OS a requirement?

**Comment by erikbern** [comment]
I actually ran this on Ubuntu 16... it should be working. When you say "lots of dependencies" what in particular are you referring to?

**Comment by erikbern** [comment]
weird, does it write results though? are you able to plot?

**Comment by richarmony** [comment]
Yep, but my results are pretty similar to yours. I'm still waiting for the run on sift-128-euclidean to end, but this is my result for mnist-784-euclidean:
![test](https://user-images.githubusercontent.com/15041034/42709307-b7779278-86a5-11e8-89ec-9d6844804258.png)
and Y-Log version:
![mnist-count1-ylog](https://user-images.githubusercontent.com/15041034/42709311-b9506a34-86a5-11e8-851b-3fa6d6fef701.png)

**Comment by erikbern** [comment]
ok cool!

seems like things are working so i'm going to close this!
