### ISSUE TITLE
Website Title Isn't Very Descriptive

### ISSUE THREAD

**Issue by xaprb** [erikbern/ann-benchmarks#90]
Just a suggestion, I think having a more descriptive `<title>` tag on the website's homepage would be helpful. Right now, it's simply `ANN-Benchmarks`. It might be better as "ANN-Benchmarks: Approximate Nearest-Neighbors Algorithm Benchmarks" or something like that.

**Comment by maumueller** [comment]
Nice suggestion @xaprb, I've updated the title.
