### ISSUE TITLE
Run ONNG for nytimes

### ISSUE THREAD

**Issue by masajiro** [erikbern/ann-benchmarks#99]
@maumueller 
I resolved the problem (#93) of the results due to invalid zero vectors in the queries. Sorry for troubling you, but could you rebuild NGT and recreate results for the nytimes dataset?
Thank you in advance.

**Comment by erikbern** [comment]
@masajiro what's preventing you from doing it yourself?

**Comment by masajiro** [comment]
@erikbern 
Since I have already confirmed that the updated ONNG clearly improved its results for the nytimes dataset on my local environment, I would like you to update only ONNG results in the [figure](https://github.com/erikbern/ann-benchmarks#nytimes-256-angular).
Do you mean that you can replace the figures with figures that I made on my local environment?

**Comment by erikbern** [comment]
@masajiro we generally re-run the benchmarks every 3-4 months or so. maybe it's time to do it again. i think it would be a lot of work to do it ad-hoc any time there's library updates.

you can also go ahead and do it yourself if you want to update the repo – can run everything on a c5.4xlarge in AWS

**Comment by yurymalkov** [comment]
@masajiro @erikbern 
If there are zero vectors in the test then it is a test bed issue which affects all algorithms. 
So, I think, removing the zero vectors from the datasets is the right solution.
